leftnav:
- identifier: 3d41a53d-eb49-6964-154a-68915d825c3d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 6b7b9760-a93e-6366-363e-18aa792baa48
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 11a083c2-7251-0287-41e6-54784d86363b
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 9b84782c-e584-0689-a998-0228b6218bbc
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 2fe4c0af-6394-da86-282d-2c11aa8992de
  name: Recitations
  pageRef: /pages/recitations
  weight: 50
- identifier: 8db023f2-d8ec-7253-d926-88a30e7c44bb
  name: Assignments
  pageRef: /pages/assignments
  weight: 60
- identifier: 8afa5fc2-30ba-fc0d-8491-0ca406659fd2
  name: Exams
  pageRef: /pages/exams
  weight: 70
